Px to em
slate-studio/kube pull request #2
Opened 2017-07-20 15:45 UTC by stanislavshylo

2017-07-20 19:21 UTC, alexkravets commented
Do not change file formatting, only change values. Keep the source as much unchanged as possible. I mean places like this: http://files.slatestudio.com/ldkS

2017-07-20 19:21 UTC, alexkravets requested changes

2017-07-20 19:21 UTC, alexkravets commented on src/_scss/_variables.scss
> +$default-font-size: 16px;
What's the point of having this, just use `$font-size` variable.

2017-07-20 19:21 UTC, alexkravets commented on src/_scss/functions.scss
> +
Remove empty lines

2017-07-20 19:21 UTC, alexkravets commented on src/_scss/functions.scss
> +
Follow code convention and rename to `_functions.scss`

2017-07-20 19:21 UTC, alexkravets commented on src/_scss/functions.scss
> +//Convert px to em
`// Calculate em from px`

2017-07-20 19:22 UTC, alexkravets commented
Change version to `v6.2.0`

2017-07-21 06:07 UTC, alexkravets requested changes

2017-07-21 06:07 UTC, alexkravets commented on src/_scss/_variables.scss
> +@function em($pixels, $context: $font-size) {
Rename `$context` to `$base-font-size`

2017-07-21 06:12 UTC, stanislavshylo commented
function `em` and $font-size should be at top of file `src/_scss/_variables.scss`

2017-07-21 07:18 UTC, merged